{
  lib,
  config,
  pkgs,
  ...
}:
let
  inherit (config) homelab;
  service = "endurain";
  cfg = homelab.services.${service};
  engine = config.virtualisation.oci-containers.backend;
in
{
  options.homelab.services.${service} = {
    enable = lib.mkEnableOption {
      description = "Enable ${service}";
    };
    url = lib.mkOption {
      type = lib.types.str;
      default = "${service}.${homelab.baseDomain}";
    };
    port = lib.mkOption {
      type = lib.types.port;
      default = 7451;
    };
    monitoredServices = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "${engine}-${service}-app"
        "${engine}-${service}-postgres"
      ];
    };
    configDir = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/${service}";
    };
    environmentFile = lib.mkOption {
      type = lib.types.path;
    };
  };
  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.configDir}/data 0755 root root -"
      "d ${cfg.configDir}/logs 0755 root root -"
      "d ${cfg.configDir}/db 0755 root root -"
    ];
    systemd.services = {
      "${engine}-endurain-app" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [ "${engine}-network-endurain_default.service" ];
        requires = [ "${engine}-network-endurain_default.service" ];
        partOf = [ "${engine}-compose-endurain-root.target" ];
        wantedBy = [ "${engine}-compose-endurain-root.target" ];
      };
      "${engine}-endurain-postgres" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [ "${engine}-network-endurain_default.service" ];
        requires = [ "${engine}-network-endurain_default.service" ];
        partOf = [ "${engine}-compose-endurain-root.target" ];
        wantedBy = [ "${engine}-compose-endurain-root.target" ];
      };
      "${engine}-network-endurain_default" = {
        path = [ pkgs.${engine} ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "${engine} network rm -f endurain_default";
        };
        script = ''
          ${engine} network inspect endurain_default || ${engine} network create endurain_default
        '';
        partOf = [ "${engine}-compose-endurain-root.target" ];
        wantedBy = [ "${engine}-compose-endurain-root.target" ];
      };

    };
    virtualisation.oci-containers.containers = {
      endurain-app = {
        image = "ghcr.io/endurain-project/endurain:latest";
        environmentFiles = [ cfg.environmentFile ];
        volumes = [
          "${cfg.configDir}/data:/app/backend/data:rw"
          "${cfg.configDir}/logs:/app/backend/logs:rw"
        ];
        ports = [
          "${if homelab.services.reverseProxy.enable then "127.0.0.1:" else ""}${toString cfg.port}:8080/tcp"
        ];
        dependsOn = [ "endurain-postgres" ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=endurain"
          "--network=endurain_default"
        ];
      };

      endurain-postgres = {
        image = "docker.io/postgres:17.5";
        environmentFiles = [ cfg.environmentFile ];
        volumes = [
          "${cfg.configDir}/db:/var/lib/postgresql/data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--health-cmd=pg_isready -U endurain"
          "--health-interval=5s"
          "--health-retries=5"
          "--health-timeout=5s"
          "--network-alias=postgres"
          "--network=endurain_default"
        ];
      };
    };
    systemd.targets."${engine}-compose-endurain-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

    networking.firewall = lib.mkMerge [
      (lib.mkIf (!homelab.services.reverseProxy.enable) {
        allowedTCPPorts = [ cfg.port ];
      })
    ];
    services.caddy.virtualHosts."${cfg.url}" = {
      useACMEHost = homelab.baseDomain;
      extraConfig = ''
        reverse_proxy http://127.0.0.1:${toString cfg.port}
      '';
    };
  };
}
