{
 "title": "DNS",
 "description": "Shows stats from the selected Blocky instance",
 "tags": [ "DNS" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(blocky_build_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "description": "current service state",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "stat",
   "description": "Is blocking enabled?",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_blocking_enabled{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Denylist entries total",
   "type": "stat",
   "description": "Number of denylist entries",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(blocky_denylist_cache_entries{job=\"$job\"}) or sum(blocky_denylist_cache{job=\"$job\"})) / sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=~\"$job\"})/sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Queries blocked",
   "type": "stat",
   "description": "Percentage of blocked queries",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total{job=\"$job\",response_type=\"BLOCKED\"}[$__range])) / sum(increase(blocky_query_total{job=\"$job\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(blocky_query_total{job=\"$job\"}[5m])) * 60",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "stat",
   "description": "Average query response time for all query types",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(blocky_request_duration_seconds_sum{job=\"$job\"}[$__rate_interval])) / sum(rate(blocky_request_duration_seconds_count{job=\"$job\"}[$__rate_interval])))\nor\n(sum(rate(blocky_request_duration_ms_sum{job=\"$job\"}[$__rate_interval])) / sum(rate(blocky_request_duration_ms_count{job=\"$job\"}[$__rate_interval])) / 1000)"
    }
   ]
  },
  {
   "title": "Prefetch Hit ratio",
   "type": "stat",
   "description": "How many of cached entries were prefetched automatically",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_prefetch_hits_total{job=\"$job\"}[$__range])) / (sum(increase(blocky_cache_hits_total{job=\"$job\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss ratio",
   "type": "stat",
   "description": "Cache Hit/Miss ratio. 100 % means, all queries could be answered from the cache, 0% - all queries must be resolved via external DNS",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_cache_hits_total{job=\"$job\"}[$__range])) / (sum(increase(blocky_cache_hits_total{job=\"$job\"}[$__range])) + sum(increase(blocky_cache_misses_total{job=\"$job\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Query Count Total",
   "type": "stat",
   "description": "Number of all queries. Shows the last value",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_query_total{job=\"$job\"}[$__range]))) "
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "description": "Time from request to upstream (unbound)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_seconds_bucket{job=\"$job\",response_type=\"RESOLVED\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (reason) (ceil(increase(blocky_response_total{job=\"$job\"}[$__range]))))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Query per Client",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (client) (ceil(increase(blocky_query_total{job=\"$job\"}[$__range]))))",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Query by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (type) (ceil(increase(blocky_query_total{job=\"$job\"}[$__range]))))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Response Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (response_type) (ceil(increase(blocky_response_total{job=\"$job\"}[$__range]))))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (response_code) (ceil(increase(blocky_response_total[$__range]))))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Request rate per client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client) (rate(blocky_query_total{job=\"$job\"}[5m])) * 60",
     "legendFormat": " {{client}}"
    }
   ]
  }
 ]
}